### ISSUE TITLE
Bundle size tracking

### ISSUE THREAD

**Issue by rabelloo** [onfido/castor#118]
Include bundle size checks in our CI, like [bundlesize](https://github.com/siddharthkp/bundlesize) or [bundlewatch](https://github.com/bundlewatch/bundlewatch),
so that we keep Castor under a certain size threshold.

**Comment by josokinas** [comment]
Maybe we could also do the same for https://github.com/onfido/castor-icons 🤔

**Comment by josokinas** [comment]
And also for https://github.com/onfido/castor-tokens now 😏
