### ISSUE TITLE
Component name not shown on Storybook code snippet when withRef is used

### ISSUE THREAD

**Issue by josokinas** [onfido/castor#151]
When a component is using `withRef`, a name is no more visible on a code snippet of Storybook, e.g.:

<img width="1017" alt="Screenshot 2021-01-07 at 18 39 06" src="https://user-images.githubusercontent.com/20243687/103918685-02e33e00-5107-11eb-817b-2c111a8b27f3.png">

**Comment by rabelloo** [comment]
Easy workaround is to add `displayName` on each component
```tsx
const Input = withRef(...);
Input.displayName = 'Input';
```

I don't think there's a way that `withRef` can do it without any explicit name giving, that'd be nice 😞 
But other ideas:

```tsx
const Input = withRef('Input', () => {});
const Input = withRef(function Input(){ });
```
