### ISSUE TITLE
Switch to different PR preview provider

### ISSUE THREAD

**Issue by josokinas** [onfido/castor#159]
For example to Netflify.

This is because current requires using `pull_request_target` that [has security issue](https://securitylab.github.com/research/github-actions-preventing-pwn-requests).

**Comment by rabelloo** [comment]
With the security issue resolved, do we still need to switch providers?

**Comment by josokinas** [comment]
Yes, because it won't be building previews for PRs from forks.

**Comment by josokinas** [comment]
Please note this will also allow to switch back to native GitHub's Dependabot.

**Comment by posthardcode** [comment]
Successfully switched to Vercel; closing.
