### ISSUE TITLE
Document Sass theme usage

### ISSUE THREAD

**Issue by rabelloo** [onfido/castor#37]
Unlike TypeScript, Sass code suggestions are not as advanced and inline exploration of the API is unreliable.

Therefore, it'd be nice to document Sass themes in a documentation Story so that consumers can better understand the API surface, without needing to dive into code.

It'd probably fit nicely in the `core` area of the documentation as `themes`.

![image](https://user-images.githubusercontent.com/18623773/101021003-36123a80-3567-11eb-9654-d15c4dc2459b.png)

It'd repeat most of what is in the README, but still might be valuable for code snippets and being in the same place as other docs.

**Comment by josokinas** [comment]
It's definetly nice to have, however probably [with v1.0.0](https://github.com/onfido/castor/milestone/1) not many will use custom themes, we might leave this for any later milestone.

**Comment by josokinas** [comment]
Addressed with https://github.com/onfido/castor/pull/401
