### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by coreyhume** [onfido/castor#61]
Implement the Search component.

**Comment by josokinas** [comment]
I don't see a suggestion for such component, maybe we could use https://www.uiguideline.com/components/input and change behaviour/appearance based on type selected.

**Comment by rabelloo** [comment]
I'd prefer a separate component as it introduces slightly different markup, unless we want consumers to provide the icon, for example:

```tsx
<div class="ods-search">
  <Input type="search" />
  <Icon name="search" />
</div>
```

Not to mention the container is needed regardless, because of icon positioning.

I'd prefer the simpler API, thus a component that composes Input + Icon:

```ts
<Search />
```
