### ISSUE TITLE
Font helper requires React types

### ISSUE THREAD

**Issue by rabelloo** [onfido/castor#811]
We should make it agnostic, and make `csstypes` a dependency instead so that `react` is not required.

https://github.com/onfido/castor/blob/main/packages/core/src/helpers/font/font.ts#L2

**Comment by josokinas** [comment]
Looks like it is only defined as `string | number`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1542

**Comment by rabelloo** [comment]
You're right, we could even skip `csstypes` altogether and just roll our own types.
